import "~/styles/globals.css";
import MyButton from "./MyButton";
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import {  ClerkProvider,  SignInButton,  SignedIn,  SignedOut,  UserButton} from '@clerk/nextjs'



export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
        
          <SignedOut>
            <SignInButton />
          </SignedOut>
          <SignedIn>
            <UserButton />
          </SignedIn>
          {children}
        <MyButton></MyButton>
        </body>
      </html>
    </ClerkProvider>
  )
}

